# Site settings
title: kiho's blog
email: syspro86@gmail.com
description:
url: "http://zsoo.net"
#twitter_username:
github_username: syspro86

# Build settings
markdown: kramdown

disqus_url: syspro86.disqus.com
disqus_id: syspro86

permalink: /post/:year-:month-:day-:title.html
timezone: "Asia/Seoul"

#sass:
#  sass_dir: _sass
#  style: compressed

remote_theme: pages-themes/primer
plugins:
  - jekyll-remote-theme
